server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/appdb
    username: app
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: false   # let auth-service run migrations

kafka:
  bootstrap-servers: kafka:9092